
package es.unican.ss.usweatherservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "USWeatherService", targetNamespace = "http://www.unican.es/ss/USWeatherService", wsdlLocation = "http://localhost:8080/ode/processes/USWeatherService?wsdl")
public class USWeatherService
    extends Service
{

    private final static URL USWEATHERSERVICE_WSDL_LOCATION;
    private final static WebServiceException USWEATHERSERVICE_EXCEPTION;
    private final static QName USWEATHERSERVICE_QNAME = new QName("http://www.unican.es/ss/USWeatherService", "USWeatherService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ode/processes/USWeatherService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USWEATHERSERVICE_WSDL_LOCATION = url;
        USWEATHERSERVICE_EXCEPTION = e;
    }

    public USWeatherService() {
        super(__getWsdlLocation(), USWEATHERSERVICE_QNAME);
    }

    public USWeatherService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USWEATHERSERVICE_QNAME, features);
    }

    public USWeatherService(URL wsdlLocation) {
        super(wsdlLocation, USWEATHERSERVICE_QNAME);
    }

    public USWeatherService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USWEATHERSERVICE_QNAME, features);
    }

    public USWeatherService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public USWeatherService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns USWeatherServicePortType
     */
    @WebEndpoint(name = "USWeatherServicePort")
    public USWeatherServicePortType getUSWeatherServicePort() {
        return super.getPort(new QName("http://www.unican.es/ss/USWeatherService", "USWeatherServicePort"), USWeatherServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns USWeatherServicePortType
     */
    @WebEndpoint(name = "USWeatherServicePort")
    public USWeatherServicePortType getUSWeatherServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.unican.es/ss/USWeatherService", "USWeatherServicePort"), USWeatherServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USWEATHERSERVICE_EXCEPTION!= null) {
            throw USWEATHERSERVICE_EXCEPTION;
        }
        return USWEATHERSERVICE_WSDL_LOCATION;
    }

}
