
package es.unican.ss.usweatherservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "USWeatherServicePortType", targetNamespace = "http://www.unican.es/ss/USWeatherService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.cdyne.ws.weatherws.ObjectFactory.class,
    es.unican.ss.usweatherservice.ObjectFactory.class,
    es.unican.ss.uszipservice.ObjectFactory.class
})
public interface USWeatherServicePortType {


    /**
     * 
     * @param params
     * @return
     *     returns es.unican.ss.usweatherservice.GetTemperatureResponse
     */
    @WebMethod(action = "http://www.unican.es/ss/USWeatherService/temperature")
    @WebResult(name = "getTemperatureResponse", targetNamespace = "http://www.unican.es/ss/USWeatherService", partName = "params")
    public GetTemperatureResponse getTemperature(
        @WebParam(name = "getTemperatureRequest", targetNamespace = "http://www.unican.es/ss/USWeatherService", partName = "params")
        GetTemperatureRequest params);

    /**
     * 
     * @param params
     * @return
     *     returns es.unican.ss.usweatherservice.GetHumidityResponse
     */
    @WebMethod(action = "http://www.unican.es/ss/USWeatherService/humidity")
    @WebResult(name = "getHumidityResponse", targetNamespace = "http://www.unican.es/ss/USWeatherService", partName = "params")
    public GetHumidityResponse getHumidity(
        @WebParam(name = "getHumidityRequest", targetNamespace = "http://www.unican.es/ss/USWeatherService", partName = "params")
        GetHumidityRequest params);

}
